### ISSUE TITLE
Android 12: plugin crashes because of FLAG_IMMUTABLE or FLAG_MUTABLE to be specified when creating a PendingIntent

### ISSUE THREAD

**Issue by NorthFred** [ghenry22/cordova-music-controls-plugin#81]
On Android 12, this plugin crashes with following error (excerpt from crash logs in Google Play Console):

```
java.lang.IllegalArgumentException: 
  at android.app.PendingIntent.checkFlags (PendingIntent.java:382)
  at android.app.PendingIntent.getBroadcastAsUser (PendingIntent.java:673)
  at android.app.PendingIntent.getBroadcast (PendingIntent.java:660)
  at com.homerours.musiccontrols.MusicControlsNotification.createBuilder (MusicControlsNotification.java:176)
  at com.homerours.musiccontrols.MusicControlsNotification.updateNotification (MusicControlsNotification.java:76)
  at com.homerours.musiccontrols.MusicControls$2.run (MusicControls.java:155)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
  at java.lang.Thread.run (Thread.java:920)
```

My project was created with latest Ionic 6 and Capacitor. There are no issues on Android 11.

When running it on Android Emulator (API 31), the app crashes completely with this error info:

```
D/EGL_emulation: app_time_stats: avg=110.80ms min=9.52ms max=286.26ms count=9
E/AndroidRuntime: FATAL EXCEPTION: pool-2-thread-1
    Process: xx.xxxxxxxx.xx, PID: 2353
    java.lang.IllegalArgumentException: xx.xxxxxxxx.xx: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
        at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
        at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:645)
        at android.app.PendingIntent.getBroadcast(PendingIntent.java:632)
        at com.homerours.musiccontrols.MusicControlsNotification.createBuilder(MusicControlsNotification.java:176)
        at com.homerours.musiccontrols.MusicControlsNotification.updateNotification(MusicControlsNotification.java:76)
        at com.homerours.musiccontrols.MusicControls$2.run(MusicControls.java:155)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:920)
```

**Comment by jlherren** [comment]
I have the same issue after upgrading `cordova-android` from 10.1 to 11.0 (which now supports API levels 31 and 32). I have not found a way to make this work.

**Comment by bhandaribhumin** [comment]
Hi, @jlherren I think https://github.com/bhandaribhumin/cordova-plugin-media-session/commits/anroid-sdk31%2B these commit help you to fix your problem, I'm still working on this brach.

**Comment by ljudbane** [comment]
I've created a fork of this plugin with the addition of FLAG_IMMUTABLE in every place that caused the crash. There are no more crashes in my tests. The fork is here: https://github.com/ljudbane/cordova-plugin-music-controls2.

I've also created a fork of cordova-plugin-background-mode, because it has the same problem: https://github.com/ljudbane/cordova-plugin-background-mode. I use these 2 plugins together, so i'm putting it here if anyone has the same problem.

The necessary changes are in the last commit of both repos. To use the fork, you need to include its link in package.json, for example like:
```
"cordova-plugin-music-controls2": "git+https://github.com/ljudbane/cordova-plugin-music-controls2.git",
```

**Comment by NorthFred** [comment]
@ljudbane Great work! I can confirm your fork [ https://github.com/ljudbane/cordova-plugin-music-controls2](https://github.com/ljudbane/cordova-plugin-music-controls2) works on Android 11 and 12. The emulator crash no longer reproduces either.

**Comment by bikubi** [comment]
can confirm that @ljudbane's fork fixes crashes; Android 13 on a Pixel 4. Also my Android 10 got fixed, which suddenly started crashing, too. (Had to bump targetSdk up to 31...)

**Comment by ghenry22** [comment]
I just published an update for the plugin to npm which should resolve this as well.  Thanks for all the feedback on this one!
